columns:
  url: object
  domain: object
  url_length: int64
  domain_length: int64
  tld: object
  url_entropy: float64
  sub_domain: int64
  digit_count: int64
  special_char_count: int64
  slash_count: int64
  https_flag: int64
  domain_entropy: float64
  keyword_flag: int64
  ip_flag: int64
  hyphen_count: int64
  query_length: int64
  at_flag: int64
  label: int64

target_column: label

numerical_columns:
  - url_length
  - domain_length
  - url_entropy
  - sub_domain
  - digit_count
  - special_char_count
  - slash_count
  - https_flag
  - domain_entropy
  - keyword_flag
  - ip_flag
  - hyphen_count
  - query_length
  - at_flag